
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               James Hung
tagline:             'Software and other unrelated bits'
description:         "Mostly writing about things I've come across as a Software Developer through hobby and profession."
url:                 http://jamhung.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              James Hung
  url:               https://github.com/jamhung
  email:             jhung86@gmail.com

# Custom vars
version:             1.0.0
